In [14]:
# importing the required libraries
import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials

In [17]:
# # define the scope
# scope = ['https://spreadsheets.google.com/feeds']

# # add credentials to the account
# creds = ServiceAccountCredentials.from_json_keyfile_name('add_json_file_here.json', scope)

# # authorize the clientsheet 
# client = gspread.authorize(creds)

In [45]:
from Google import Create_Servicefrom __future__ import print_function

import os.path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# If modifying these scopes, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/documents.readonly']

# The ID of a sample document.
DOCUMENT_ID = '195j9eDD3ccgjQRttHhJPymLJUCOUjs-jmwTrekvdjFE'

SyntaxError: invalid syntax (24154923.py, line 1)

In [46]:
def main():
    """Shows basic usage of the Docs API.
    Prints the title of a sample document.
    """
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    try:
        service = build('docs', 'v1', credentials=creds)

        # Retrieve the documents contents from the Docs service.
        document = service.documents().get(documentId=DOCUMENT_ID).execute()

        print('The title of the document is: {}'.format(document.get('title')))
    except HttpError as err:
        print(err)

In [47]:
  # pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

In [2]:
import gspread

In [4]:
# importing the required libraries
import gspread
import pandas as pd
from oauth2client.service_account import ServiceAccountCredentials

In [27]:
# define the scope
scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']

# add credentials to the account
creds = ServiceAccountCredentials.from_json_keyfile_name('fiap3sis-3b74d339060b.json', scope)

# authorize the clientsheet
client = gspread.authorize(creds)

In [36]:
# get the instance of the Spreadsheet
sheet = client.open('teste_fiap_diego')

# get the first sheet of the Spreadsheet
sheet_instance = sheet.get_worksheet(2)

In [37]:
# get the total number of columns
sheet_instance.col_count
## >> 26


# get the value at the specific cell
sheet_instance.cell(col=3,row=2)
## >> <Cell R2C3 '63881'>

In [ ]:
# get all the records of the data
records_data = sheet_instance.get_all_records()

# view the data
records_data

In [39]:
# convert the json to dataframe
records_df = pd.DataFrame.from_dict(records_data)

# view the top records
records_df.head()

      carros      pais  quantidade
0     toyota     japao           2
1  volkswage  alemanha           3
2  volkswage  alemanha           4
3  volkswage  alemanha           4
4  volkswage  alemanha           2

In [43]:
# add a sheet with 20 rows and 2 columns
# sheet.add_worksheet(rows=20,cols=2,title='runs')

# get the instance of the second sheet
sheet_runs = sheet.get_worksheet(1)

In [42]:
sheet_runs.insert_rows(runs.values.tolist())

{'spreadsheetId': '1I-T8eg390sxC7JVMR61YmqBXgCqwXKH0FtwHX5KUdfM',
 'updates': {'spreadsheetId': '1I-T8eg390sxC7JVMR61YmqBXgCqwXKH0FtwHX5KUdfM',
  'updatedRange': 'runs!A1:B3',
  'updatedRows': 3,
  'updatedColumns': 2,
  'updatedCells': 6}}

In [41]:

# number of runs by each batsman
runs = records_df.groupby(['pais'])['quantidade'].count().reset_index()
runs

       pais  quantidade
0  alemanha          10
1    brasil           4
2     japao           6

In [51]:
# def main():
#     """Shows basic usage of the Sheets API.
#     Prints values from a sample spreadsheet.
#     """
#     creds = None
#     # The file token.json stores the user's access and refresh tokens, and is
#     # created automatically when the authorization flow completes for the first
#     # time.
#     if os.path.exists('token.json'):
#         creds = Credentials.from_authorized_user_file('token.json', SCOPES)
#     # If there are no (valid) credentials available, let the user log in.
#     if not creds or not creds.valid:
#         if creds and creds.expired and creds.refresh_token:
#             creds.refresh(Request())
#         else:
#             flow = InstalledAppFlow.from_client_secrets_file(
#                 'fiap3sis-3b74d339060b.json', SCOPES)
#             creds = flow.run_local_server(port=0)
#         # Save the credentials for the next run
#         with open('token.json', 'w') as token:
#             token.write(creds.to_json())

#     try:
#         service = build('sheets', 'v4', credentials=creds)

#         # Call the Sheets API
#         sheet = service.spreadsheets()
#         result = sheet.values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID,
#                                     range=SAMPLE_RANGE_NAME).execute()
#         values = result.get('values', [])

#         if not values:
#             print('No data found.')
#             return

#         print('Name, Major:')
#         for row in values:
#             # Print columns A and E, which correspond to indices 0 and 4.
#             print('%s, %s' % (row[0], row[4]))
#     except HttpError as err:
#         print(err)

In [55]:
import pandas as pd
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow,Flow
from google.auth.transport.requests import Request
import os
import pickle

SCOPES = ['https://www.googleapis.com/auth/drive']

# here enter the id of your google sheet
SAMPLE_SPREADSHEET_ID_input = '1I-T8eg390sxC7JVMR61YmqBXgCqwXKH0FtwHX5KUdfM'
SAMPLE_RANGE_NAME = 'A1:AA1000'

def main():
    global values_input, service
    creds = None
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'fiap3sis-3b74d339060b.json', SCOPES) # here enter the name of your downloaded JSON file
            creds = flow.run_local_server(port=0)
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('sheets', 'v4', credentials=creds)

    # Call the Sheets API
    sheet = service.spreadsheets()
    result_input = sheet.values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID_input,
                                range=SAMPLE_RANGE_NAME).execute()
    values_input = result_input.get('values', [])

    if not values_input and not values_expansion:
        print('No data found.')

main()

df=pd.DataFrame(values_input[1:], columns=values_input[0])

ValueError: Client secrets must be for a web or installed app.

In [1]:
H(x) -> h

SyntaxError: invalid syntax (1210039442.py, line 1)

In [2]:
import hashlib

In [6]:
print(hashlib.algorithms_available)

{'sha512_224', 'blake2s', 'shake_128', 'sha3_224', 'sha384', 'sha3_256', 'ripemd160', 'sha512_256', 'whirlpool', 'sm3', 'mdc2', 'sha256', 'sha224', 'blake2b', 'sha3_512', 'md4', 'sha3_384', 'md5', 'md5-sha1', 'sha1', 'sha512', 'shake_256'}

In [5]:
hashlib.md5('123').hexdigest()

TypeError: Strings must be encoded before hashing

In [7]:
print(hashlib.md5(b'Hello World').digest())

b'\xb1\n\x8d\xb1d\xe0uA\x05\xb7\xa9\x9b\xe7.?\xe5'